### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by phozzy** [heyzec/wayland-displays#1]
I'm switching to NixOS and Hyprland. So, I found your project and tried to use it to configure displays.
I've cloned your repository, switched to the result directory and tried to run `nix run`
I'm getting the following result:
```
~/Workspaces/github.com/heyzec/wayland-displays]$ nix run
terminate called after throwing an instance of 'std::runtime_error'
  what():  No such key: switch
Aborted (core dumped)
```
Am I missing something?

**Comment by heyzec** [comment]
Hello, and thank you for showing interest in my project! Unfortunately, I haven't had enough time recently to continue working on wayland-displays, and as a result, it is not as polished as I would like it to be.

There was a bug that caused the program to crash if it was run without arguments. I've just pushed a fix for this, so it now shows a warning instead. You can now use `nix run . -- --server` and `nix run . -- --gui` to try it out.

**Comment by phozzy** [comment]
Oh... I see.
It seems that the app assumes, that the config file is already there and fails if it is absent or incomplete. And after it fails, it does not clean after itself.
```
[artur@artur:~/Workspaces/github.com/heyzec/wayland-displays]$ ./result/bin/wayland-displays --server
interface: 'zwlr_output_manager_v1', version: 4, name: 30
Scale 1.500000
Adaptive Sync: 0
Scale 1.000000
Adaptive Sync: 0
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; first invalid key: "ARRANGE"
Aborted (core dumped)

[artur@artur:~/Workspaces/github.com/heyzec/wayland-displays]$ nvim ~/.config/wayland-displays.yml

[artur@artur:~/Workspaces/github.com/heyzec/wayland-displays]$ ./result/bin/wayland-displays --server
Error binding socket: Address already in use
```
Just hope it will help to improve the app :-)

**Comment by heyzec** [comment]
Ah, that is definitely on me, I hope to be able to address these bugs sometime soon.

For now, if it helps, the config can be found in the examples/ folder:
```
cp examples/wayland-displays.yml ~/.config/wayland-displays.yml
nvim ~/.config/wayland-displays.yml
```
and the socket can be removed with
```
rm $XDG_RUNTIME_DIR/wayland-displays.sock
````

**Comment by phozzy** [comment]
Thanks! It worked!
